/* ═══════════════════════════════════════════════════════════════
   كلماتي الكويتية — ملف البيانات (words.js)

   لإضافة كلمة جديدة: انسخ أي كائن وغيّر قيمه، مع id جديد غير مكرر.
   حقول التقدم (reviewDate, correctAnswers, wrongAnswers) اتركها
   على قيمها الافتراضية — التطبيق ينسخها لكل طفل في Local Storage.

   difficulty: 1 = سهلة ⭐ ، 2 = متوسطة ⭐⭐ ، 3 = صعبة ⭐⭐⭐

   الصور: تأتي من فهرس الصور images.js (يُحمَّل قبل هذا الملف)،
   وتُدمج تلقائياً أسفل هذا الملف فيحصل كل كائن كلمة على:
     image:           المسار الأساسي  "assets/images/words/….svg"
     imageVariations: مصفوفة بدائل (ألوان/أحجام/زوايا مختلفة)
   حقل emoji هنا هو احتياطي أخير فقط إذا فشل تحميل كل الصور.
   ═══════════════════════════════════════════════════════════════ */

/* الفئات: المفتاح يُستخدم في كائنات الكلمات، والقيمة للعرض */
const WORD_CATEGORIES = {
  home:        { label: "البيت",            emoji: "🏠" },
  kitchen:     { label: "المطبخ",           emoji: "🍳" },
  school:      { label: "المدرسة",          emoji: "🏫" },
  clothes:     { label: "الملابس",          emoji: "👕" },
  animals:     { label: "الحيوانات",        emoji: "🐱" },
  food:        { label: "الأكل",            emoji: "🍚" },
  street:      { label: "الشارع",           emoji: "🚗" },
  family:      { label: "العائلة",          emoji: "👨‍👩‍👧" },
  colors:      { label: "الألوان",          emoji: "🎨" },
  expressions: { label: "تعابير كويتية",    emoji: "💬" },
};

const KUWAITI_WORDS = [

  /* ── البيت 🏠 ─────────────────────────────────────────────── */
  {
    id: 1,
    kuwaitiWord: "دريشة",
    tts: "دِرِيشَة",
    standardArabic: "نافذة",
    english: "Window",
    emoji: "🪟",
    example: "بطّل الدريشة، الجو حلو!",
    category: "home",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 2,
    kuwaitiWord: "حوش",
    tts: "حُوش",
    standardArabic: "فناء البيت",
    english: "Yard",
    emoji: "🏡",
    example: "نلعب في الحوش عقب العصر.",
    category: "home",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 3,
    kuwaitiWord: "مخدة",
    tts: "مِخَدَّة",
    standardArabic: "وسادة",
    english: "Pillow",
    emoji: "🛏️",
    example: "مخدتي ناعمة وأحبها وايد.",
    category: "home",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 4,
    kuwaitiWord: "دولاب",
    tts: "دُولاب",
    standardArabic: "خزانة",
    english: "Closet",
    emoji: "🗄️",
    example: "رتبت هدومي في الدولاب.",
    category: "home",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── المطبخ 🍳 ────────────────────────────────────────────── */
  {
    id: 5,
    kuwaitiWord: "قوطي",
    tts: "قُوطِي",
    standardArabic: "علبة",
    english: "Can",
    emoji: "🥫",
    example: "عطني قوطي العصير من الثلاجة.",
    category: "kitchen",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 6,
    kuwaitiWord: "استكانة",
    tts: "اِسْتِكانَة",
    standardArabic: "كوب شاي صغير",
    english: "Tea glass",
    emoji: "🍵",
    example: "يدتي تشرب الچاي في استكانة.",
    category: "kitchen",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 7,
    kuwaitiWord: "ملاس",
    tts: "مَلاس",
    standardArabic: "ملعقة",
    english: "Spoon",
    emoji: "🥄",
    example: "أمي تحرّك الشوربة بالملاس.",
    category: "kitchen",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 8,
    kuwaitiWord: "جدر",
    tts: "جِدِر",
    standardArabic: "قِدر",
    english: "Cooking pot",
    emoji: "🍲",
    example: "ريحة الأكل من الجدر تشهّي!",
    category: "kitchen",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── المدرسة 🏫 ───────────────────────────────────────────── */
  {
    id: 9,
    kuwaitiWord: "جنطة",
    tts: "جَنْطَة",
    standardArabic: "حقيبة",
    english: "Bag",
    emoji: "🎒",
    example: "حطيت كتبي في جنطتي.",
    category: "school",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 10,
    kuwaitiWord: "براية",
    tts: "بَرّايَة",
    standardArabic: "مبراة",
    english: "Sharpener",
    emoji: "✏️",
    example: "بريت قلمي بالبراية.",
    category: "school",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 11,
    kuwaitiWord: "دفتر",
    tts: "دَفْتَر",
    standardArabic: "كراسة",
    english: "Notebook",
    emoji: "📓",
    example: "أكتب واجبي في الدفتر.",
    category: "school",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الملابس 👕 ───────────────────────────────────────────── */
  {
    id: 12,
    kuwaitiWord: "دشداشة",
    tts: "دِشْداشَة",
    standardArabic: "ثوب رجالي",
    english: "Dishdasha",
    emoji: "👕",
    example: "أبوي يلبس دشداشة بيضاء.",
    category: "clothes",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 13,
    kuwaitiWord: "جوتي",
    tts: "جُوتِي",
    standardArabic: "حذاء",
    english: "Shoes",
    emoji: "👟",
    example: "جوتيي اليديد لونه أزرق.",
    category: "clothes",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 14,
    kuwaitiWord: "غترة",
    tts: "غِتْرَة",
    standardArabic: "غطاء رأس للرجال",
    english: "Ghutra",
    emoji: "🧣",
    example: "جدي يلبس غترة بيضاء يوم الجمعة.",
    category: "clothes",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 15,
    kuwaitiWord: "نعال",
    tts: "نِعال",
    standardArabic: "حذاء خفيف",
    english: "Slippers",
    emoji: "🩴",
    example: "البس نعالك قبل لا تطلع الحوش.",
    category: "clothes",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الحيوانات 🐱 ─────────────────────────────────────────── */
  {
    id: 16,
    kuwaitiWord: "قطو",
    tts: "قَطُو",
    standardArabic: "قطة",
    english: "Cat",
    emoji: "🐱",
    example: "القطو الصغير يشرب حليب.",
    category: "animals",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 17,
    kuwaitiWord: "دياية",
    tts: "دِيايَة",
    standardArabic: "دجاجة",
    english: "Chicken",
    emoji: "🐔",
    example: "الدياية عندها صيصان صغار.",
    category: "animals",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 18,
    kuwaitiWord: "بعير",
    tts: "بِعِير",
    standardArabic: "جمل",
    english: "Camel",
    emoji: "🐪",
    example: "شفت بعير كبير في البر.",
    category: "animals",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 19,
    kuwaitiWord: "سمچة",
    tts: "سِمْچَة",
    standardArabic: "سمكة",
    english: "Fish",
    emoji: "🐟",
    example: "في بحر الكويت سمچ وايد.",
    category: "animals",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الأكل 🍚 ─────────────────────────────────────────────── */
  {
    id: 20,
    kuwaitiWord: "صمونة",
    tts: "صَمُّونَة",
    standardArabic: "خبز صغير",
    english: "Bread roll",
    emoji: "🍞",
    example: "كليت صمونة بالجبن حق الريوق.",
    category: "food",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 21,
    kuwaitiWord: "عيش",
    tts: "عَيْش",
    standardArabic: "أرز",
    english: "Rice",
    emoji: "🍚",
    example: "اليوم غدانا عيش ودياي.",
    category: "food",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 22,
    kuwaitiWord: "ماي",
    tts: "ماي",
    standardArabic: "ماء",
    english: "Water",
    emoji: "💧",
    example: "أشرب ماي وايد عشان صحتي.",
    category: "food",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 23,
    kuwaitiWord: "ريوق",
    tts: "رَيُوق",
    standardArabic: "فطور",
    english: "Breakfast",
    emoji: "🍳",
    example: "شنو ريوقك اليوم؟",
    category: "food",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الشارع 🚗 ────────────────────────────────────────────── */
  {
    id: 24,
    kuwaitiWord: "موتر",
    tts: "مُوتَر",
    standardArabic: "سيارة",
    english: "Car",
    emoji: "🚗",
    example: "موتر أبوي لونه أبيض.",
    category: "street",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 25,
    kuwaitiWord: "سيكل",
    tts: "سَيْكَل",
    standardArabic: "دراجة",
    english: "Bicycle",
    emoji: "🚲",
    example: "أركب سيكلي عند بيتنا.",
    category: "street",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 26,
    kuwaitiWord: "فريج",
    tts: "فِرِيج",
    standardArabic: "حي سكني",
    english: "Neighborhood",
    emoji: "🏘️",
    example: "بيت يدتي في نفس الفريج.",
    category: "street",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 27,
    kuwaitiWord: "درب",
    tts: "دَرْب",
    standardArabic: "طريق",
    english: "Road",
    emoji: "🛣️",
    example: "هذا الدرب يوصّل للمدرسة.",
    category: "street",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── العائلة 👨‍👩‍👧 ─────────────────────────────────────────── */
  {
    id: 28,
    kuwaitiWord: "يدّة",
    tts: "يَدَّة",
    standardArabic: "جدة",
    english: "Grandma",
    emoji: "👵",
    example: "أحب أزور يدتي يوم الجمعة.",
    category: "family",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 29,
    kuwaitiWord: "يمّه",
    tts: "يُمَّه",
    standardArabic: "أمي",
    english: "Mom",
    emoji: "👩",
    example: "يمّه، أنا جوعان!",
    category: "family",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 30,
    kuwaitiWord: "عيال",
    tts: "عِيال",
    standardArabic: "أطفال",
    english: "Kids",
    emoji: "🧒",
    example: "عيال خالتي يلعبون ويّانا.",
    category: "family",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 31,
    kuwaitiWord: "بيبي",
    tts: "بِيبِي",
    standardArabic: "طفل رضيع",
    english: "Baby",
    emoji: "👶",
    example: "عندنا بيبي صغير في البيت.",
    category: "family",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الألوان 🎨 ───────────────────────────────────────────── */
  {
    id: 32,
    kuwaitiWord: "رصاصي",
    tts: "رَصاصِي",
    standardArabic: "رمادي",
    english: "Gray",
    emoji: "🩶",
    example: "لون الغيمة اليوم رصاصي.",
    category: "colors",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 33,
    kuwaitiWord: "سماوي",
    tts: "سَماوِي",
    standardArabic: "أزرق فاتح",
    english: "Sky blue",
    emoji: "🩵",
    example: "السما لونها سماوي حلو.",
    category: "colors",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 34,
    kuwaitiWord: "وردي",
    tts: "وَرْدِي",
    standardArabic: "زهري",
    english: "Pink",
    emoji: "🌸",
    example: "جنطة أختي لونها وردي.",
    category: "colors",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── تعابير كويتية 💬 ─────────────────────────────────────── */
  {
    id: 35,
    kuwaitiWord: "شلونك؟",
    tts: "شِلُونَك؟",
    standardArabic: "كيف حالك؟",
    english: "How are you?",
    emoji: "👋",
    example: "شلونك يا صديقي؟",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 36,
    kuwaitiWord: "وايد",
    tts: "وايِد",
    standardArabic: "كثير",
    english: "A lot",
    emoji: "✨",
    example: "أحب يدتي وايد.",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 37,
    kuwaitiWord: "زين",
    tts: "زَيْن",
    standardArabic: "جيد",
    english: "Good",
    emoji: "👍",
    example: "سويت زين في الاختبار!",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 38,
    kuwaitiWord: "يلّا",
    tts: "يَلّا",
    standardArabic: "هيا بنا",
    english: "Let's go",
    emoji: "🏃",
    example: "يلّا نلعب برّع!",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 39,
    kuwaitiWord: "چذي",
    tts: "چِذِي",
    standardArabic: "هكذا",
    english: "Like this",
    emoji: "☝️",
    example: "امسك القلم چذي.",
    category: "expressions",
    difficulty: 3,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 40,
    kuwaitiWord: "مشكور",
    tts: "مَشْكُور",
    standardArabic: "شكراً",
    english: "Thank you",
    emoji: "🙏",
    example: "مشكور على الهدية!",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
];

/* دمج فهرس الصور: كل كلمة تحصل على image + imageVariations من images.js */
const IMAGES = window.WORD_IMAGES || {};
KUWAITI_WORDS.forEach((w) => {
  const m = IMAGES[w.id];
  if (m) {
    w.image = m.main;                    // مثال: "assets/images/words/motar.svg"
    w.imageVariations = m.variations;    // بدائل بألوان وأحجام وزوايا مختلفة
    w.imageAlt = m.alt;
    w.needsCustomIllustration = m.needsCustomIllustration;
  } else {
    w.image = window.IMAGE_FALLBACK || null;
    w.imageVariations = [];
  }
});

/* إتاحة البيانات لملف app.js (سكربتات عادية بدون وحدات) */
window.KUWAITI_WORDS = KUWAITI_WORDS;
window.WORD_CATEGORIES = WORD_CATEGORIES;
