/* ═══════════════════════════════════════════════════════════════
   كلماتي الكويتية — ملف البيانات (words.js)

   لإضافة كلمة جديدة: انسخ أي كائن وغيّر قيمه، مع id جديد غير مكرر.
   حقول التقدم (reviewDate, correctAnswers, wrongAnswers) اتركها
   على قيمها الافتراضية — التطبيق ينسخها لكل طفل في Local Storage.

   difficulty: 1 = سهلة ⭐ ، 2 = متوسطة ⭐⭐ ، 3 = صعبة ⭐⭐⭐
   image: إيموجي كعنصر نائب — يمكن استبداله لاحقاً بمسار صورة حقيقية.
   ═══════════════════════════════════════════════════════════════ */

/* الفئات: المفتاح يُستخدم في كائنات الكلمات، والقيمة للعرض */
const WORD_CATEGORIES = {
  home:        { label: "البيت",            emoji: "🏠" },
  kitchen:     { label: "المطبخ",           emoji: "🍳" },
  school:      { label: "المدرسة",          emoji: "🏫" },
  clothes:     { label: "الملابس",          emoji: "👕" },
  animals:     { label: "الحيوانات",        emoji: "🐱" },
  food:        { label: "الأكل",            emoji: "🍚" },
  street:      { label: "الشارع",           emoji: "🚗" },
  family:      { label: "العائلة",          emoji: "👨‍👩‍👧" },
  colors:      { label: "الألوان",          emoji: "🎨" },
  expressions: { label: "تعابير كويتية",    emoji: "💬" },
};

const KUWAITI_WORDS = [

  /* ── البيت 🏠 ─────────────────────────────────────────────── */
  {
    id: 1,
    kuwaitiWord: "دريشة",
    standardArabic: "نافذة",
    english: "Window",
    image: "🪟",
    example: "بطّل الدريشة، الجو حلو!",
    category: "home",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 2,
    kuwaitiWord: "حوش",
    standardArabic: "فناء البيت",
    english: "Yard",
    image: "🏡",
    example: "نلعب في الحوش عقب العصر.",
    category: "home",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 3,
    kuwaitiWord: "مخدة",
    standardArabic: "وسادة",
    english: "Pillow",
    image: "🛏️",
    example: "مخدتي ناعمة وأحبها وايد.",
    category: "home",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 4,
    kuwaitiWord: "دولاب",
    standardArabic: "خزانة",
    english: "Closet",
    image: "🗄️",
    example: "رتبت ملابسي في الدولاب.",
    category: "home",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── المطبخ 🍳 ────────────────────────────────────────────── */
  {
    id: 5,
    kuwaitiWord: "قوطي",
    standardArabic: "علبة",
    english: "Can",
    image: "🥫",
    example: "عطني قوطي العصير من الثلاجة.",
    category: "kitchen",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 6,
    kuwaitiWord: "استكانة",
    standardArabic: "كوب شاي صغير",
    english: "Tea glass",
    image: "🍵",
    example: "يدتي تشرب الچاي في استكانة.",
    category: "kitchen",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 7,
    kuwaitiWord: "ملاس",
    standardArabic: "ملعقة",
    english: "Spoon",
    image: "🥄",
    example: "أمي تحرّك الشوربة بالملاس.",
    category: "kitchen",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 8,
    kuwaitiWord: "جدر",
    standardArabic: "قِدر",
    english: "Cooking pot",
    image: "🍲",
    example: "ريحة الأكل من الجدر تشهّي!",
    category: "kitchen",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── المدرسة 🏫 ───────────────────────────────────────────── */
  {
    id: 9,
    kuwaitiWord: "جنطة",
    standardArabic: "حقيبة",
    english: "Bag",
    image: "🎒",
    example: "حطيت كتبي في جنطتي.",
    category: "school",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 10,
    kuwaitiWord: "براية",
    standardArabic: "مبراة",
    english: "Sharpener",
    image: "✏️",
    example: "بريت قلمي بالبراية.",
    category: "school",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 11,
    kuwaitiWord: "دفتر",
    standardArabic: "كراسة",
    english: "Notebook",
    image: "📓",
    example: "أكتب واجبي في الدفتر.",
    category: "school",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الملابس 👕 ───────────────────────────────────────────── */
  {
    id: 12,
    kuwaitiWord: "دشداشة",
    standardArabic: "ثوب رجالي",
    english: "Dishdasha",
    image: "👕",
    example: "أبوي يلبس دشداشة بيضاء.",
    category: "clothes",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 13,
    kuwaitiWord: "جوتي",
    standardArabic: "حذاء",
    english: "Shoes",
    image: "👟",
    example: "جوتيي اليديد لونه أزرق.",
    category: "clothes",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 14,
    kuwaitiWord: "غترة",
    standardArabic: "غطاء رأس للرجال",
    english: "Ghutra",
    image: "🧣",
    example: "جدي يلبس غترة بيضاء يوم الجمعة.",
    category: "clothes",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 15,
    kuwaitiWord: "نعال",
    standardArabic: "حذاء خفيف",
    english: "Slippers",
    image: "🩴",
    example: "البس نعالك قبل لا تطلع الحوش.",
    category: "clothes",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الحيوانات 🐱 ─────────────────────────────────────────── */
  {
    id: 16,
    kuwaitiWord: "قطو",
    standardArabic: "قطة",
    english: "Cat",
    image: "🐱",
    example: "القطو الصغير يشرب حليب.",
    category: "animals",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 17,
    kuwaitiWord: "دياية",
    standardArabic: "دجاجة",
    english: "Chicken",
    image: "🐔",
    example: "الدياية عندها صيصان صغار.",
    category: "animals",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 18,
    kuwaitiWord: "بعير",
    standardArabic: "جمل",
    english: "Camel",
    image: "🐪",
    example: "شفت بعير كبير في البر.",
    category: "animals",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 19,
    kuwaitiWord: "سمچة",
    standardArabic: "سمكة",
    english: "Fish",
    image: "🐟",
    example: "في بحر الكويت سمچ وايد.",
    category: "animals",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الأكل 🍚 ─────────────────────────────────────────────── */
  {
    id: 20,
    kuwaitiWord: "صمونة",
    standardArabic: "خبز صغير",
    english: "Bread roll",
    image: "🍞",
    example: "كليت صمونة بالجبن حق الريوق.",
    category: "food",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 21,
    kuwaitiWord: "عيش",
    standardArabic: "أرز",
    english: "Rice",
    image: "🍚",
    example: "اليوم غدانا عيش ودياي.",
    category: "food",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 22,
    kuwaitiWord: "ماي",
    standardArabic: "ماء",
    english: "Water",
    image: "💧",
    example: "أشرب ماي وايد عشان صحتي.",
    category: "food",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 23,
    kuwaitiWord: "ريوق",
    standardArabic: "فطور",
    english: "Breakfast",
    image: "🍳",
    example: "شنو ريوقك اليوم؟",
    category: "food",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الشارع 🚗 ────────────────────────────────────────────── */
  {
    id: 24,
    kuwaitiWord: "موتر",
    standardArabic: "سيارة",
    english: "Car",
    image: "🚗",
    example: "موتر أبوي لونه أبيض.",
    category: "street",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 25,
    kuwaitiWord: "سيكل",
    standardArabic: "دراجة",
    english: "Bicycle",
    image: "🚲",
    example: "أركب سيكلي عند بيتنا.",
    category: "street",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 26,
    kuwaitiWord: "فريج",
    standardArabic: "حي سكني",
    english: "Neighborhood",
    image: "🏘️",
    example: "بيت يدتي في نفس الفريج.",
    category: "street",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 27,
    kuwaitiWord: "درب",
    standardArabic: "طريق",
    english: "Road",
    image: "🛣️",
    example: "هذا الدرب يوصّل للمدرسة.",
    category: "street",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── العائلة 👨‍👩‍👧 ─────────────────────────────────────────── */
  {
    id: 28,
    kuwaitiWord: "يدّة",
    standardArabic: "جدة",
    english: "Grandma",
    image: "👵",
    example: "أحب أزور يدتي يوم الجمعة.",
    category: "family",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 29,
    kuwaitiWord: "يمّه",
    standardArabic: "أمي",
    english: "Mom",
    image: "👩",
    example: "يمّه، أنا جوعان!",
    category: "family",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 30,
    kuwaitiWord: "عيال",
    standardArabic: "أطفال",
    english: "Kids",
    image: "🧒",
    example: "عيال خالتي يلعبون ويّانا.",
    category: "family",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 31,
    kuwaitiWord: "بيبي",
    standardArabic: "طفل رضيع",
    english: "Baby",
    image: "👶",
    example: "أختي الصغيرة بيبي حلوة.",
    category: "family",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── الألوان 🎨 ───────────────────────────────────────────── */
  {
    id: 32,
    kuwaitiWord: "رصاصي",
    standardArabic: "رمادي",
    english: "Gray",
    image: "🩶",
    example: "لون الغيمة اليوم رصاصي.",
    category: "colors",
    difficulty: 2,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 33,
    kuwaitiWord: "سماوي",
    standardArabic: "أزرق فاتح",
    english: "Sky blue",
    image: "🩵",
    example: "السما لونها سماوي حلو.",
    category: "colors",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 34,
    kuwaitiWord: "وردي",
    standardArabic: "زهري",
    english: "Pink",
    image: "🌸",
    example: "جنطة أختي لونها وردي.",
    category: "colors",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },

  /* ── تعابير كويتية 💬 ─────────────────────────────────────── */
  {
    id: 35,
    kuwaitiWord: "شلونك؟",
    standardArabic: "كيف حالك؟",
    english: "How are you?",
    image: "👋",
    example: "شلونك يا صديقي؟",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 36,
    kuwaitiWord: "وايد",
    standardArabic: "كثير",
    english: "A lot",
    image: "✨",
    example: "أحب يدتي وايد.",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 37,
    kuwaitiWord: "زين",
    standardArabic: "جيد",
    english: "Good",
    image: "👍",
    example: "سويت زين في الاختبار!",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 38,
    kuwaitiWord: "يلّا",
    standardArabic: "هيا بنا",
    english: "Let's go",
    image: "🏃",
    example: "يلّا نلعب برّع!",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 39,
    kuwaitiWord: "چذي",
    standardArabic: "هكذا",
    english: "Like this",
    image: "☝️",
    example: "امسك القلم چذي.",
    category: "expressions",
    difficulty: 3,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
  {
    id: 40,
    kuwaitiWord: "مشكور",
    standardArabic: "شكراً",
    english: "Thank you",
    image: "🙏",
    example: "مشكور على الهدية!",
    category: "expressions",
    difficulty: 1,
    reviewDate: null,
    correctAnswers: 0,
    wrongAnswers: 0,
  },
];

/* إتاحة البيانات لملف app.js (سكربتات عادية بدون وحدات) */
window.KUWAITI_WORDS = KUWAITI_WORDS;
window.WORD_CATEGORIES = WORD_CATEGORIES;
